services:
  bot:
    image: 4strodev/telegram-songs-dl:24-11-30_21-45-amd64
    restart: always
    env_file: .env
  ## If you prefer you can set the environment variables directly
  ## on the docker compose environment entry
    #environment:
      #TELEGRAM_TOKEN: "<your token>"
      #SONGS_FILE: "<songs file path>"
